spring.application.name=forohub
spring.datasource.url=jdbc:postgresql://${BD_HOST}/${BD_NAME}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.devtools.add-properties=false
server.error.include-stacktrace=never

spring.jpa.hibernate.ddl-auto=update

flyway.url=jdbc:postgresql://${BD_HOST}/${BD_NAME}
flyway.user=${BD_USER}
flyway.password=${BD_PASSWORD}
flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

api.security.token.secret=${JWT_SECRET:12345678}

